version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: candle-factory-db
    restart: always
    environment:
      MYSQL_DATABASE: candle_factory
      MYSQL_USER: candle_user
      MYSQL_PASSWORD: i-Ker!
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: